markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

module:
  imports:
    # Path is relative to themes directory for project using heptane
    # Crux is included as a git submodule within heptane
    - path: heptane/crux
      mounts:
        - source: markup/render-heading.html
          target: layouts/_default/_markup/render-heading.html
